// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpCPNR3kstuT8WL9l1y974kcIMiFWCAM',
    appId: '1:310722748852:web:f70d0d045573f4cf1392e1',
    messagingSenderId: '310722748852',
    projectId: 'africanstraw-e03e1',
    authDomain: 'africanstraw-e03e1.firebaseapp.com',
    storageBucket: 'africanstraw-e03e1.appspot.com',
    measurementId: 'G-2197P4DTDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9CDxcGAe_0FHRgLQMCSzTe8yD0kuW_xY',
    appId: '1:310722748852:android:aa18e44d2a76eef11392e1',
    messagingSenderId: '310722748852',
    projectId: 'africanstraw-e03e1',
    storageBucket: 'africanstraw-e03e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bjFU3DDdNQiaFab4j4FXPx1QwEeZiiI',
    appId: '1:310722748852:ios:dd83f4c90a4b3e831392e1',
    messagingSenderId: '310722748852',
    projectId: 'africanstraw-e03e1',
    storageBucket: 'africanstraw-e03e1.appspot.com',
    iosBundleId: 'com.africanstraw.africanstraw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bjFU3DDdNQiaFab4j4FXPx1QwEeZiiI',
    appId: '1:310722748852:ios:dd83f4c90a4b3e831392e1',
    messagingSenderId: '310722748852',
    projectId: 'africanstraw-e03e1',
    storageBucket: 'africanstraw-e03e1.appspot.com',
    iosBundleId: 'com.africanstraw.africanstraw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcpCPNR3kstuT8WL9l1y974kcIMiFWCAM',
    appId: '1:310722748852:web:f0ad4aaeb0ea79421392e1',
    messagingSenderId: '310722748852',
    projectId: 'africanstraw-e03e1',
    authDomain: 'africanstraw-e03e1.firebaseapp.com',
    storageBucket: 'africanstraw-e03e1.appspot.com',
    measurementId: 'G-F0RH7HKTTR',
  );

}